users:
  cc_user:
    password: cc_user
    portals:
      - ClearCATS:
        - User
  cc_admin:
    password: cc_admin
    portals:
      - ClearCATS:
        - Admin
  pfr957:
    password: pfr957
    portals:
      - ClearCATS:
        - Admin
  faculty:
    password: faculty
    portals:
      - ClearCATS:
  cecd_user:
    password: cecd_user
    portals:
      - ClearCATS:
        - Admin: [4619]
  crc_user:
    password: crc_user
    portals:
      - ClearCATS:
        - Admin: [4620]
  cti_user:
    password: cti_user
    portals:
      - ClearCATS:
        - Admin: [4621]
  cerc_user:
    password: cerc_user
    portals:
      - ClearCATS:
        - Admin: [4622]
  nubic_user:
    password: nubic_user
    portals:
      - ClearCATS:
        - Admin: [4623]
  wakibbe:
    password: wakibbe
    portals:
      - ClearCATS:
        - Admin: [4623]
  rsp_user:
    password: rsp_user
    portals:
      - ClearCATS:
        - Admin: [4624]
  te_user:
    password: te_user
    portals:
      - ClearCATS:
        - Admin: [4626]
  pgreenld:
    password: pgreenld
  awa272:
    password: awa272
  zbu468:
    password: zbu468
  asdf:
    password: asdf
